const fakeFile = [
    {
        project: { id: 1},
        name: "index",
        extension: "html",
        type: "file",
        content: `
<div id="app">
<p class="blue">Hello, world!</p>
</div>
        `,
        language: "html",
    },
    {
        project: { id: 1},
        name: "style",
        extension: "css",
        type: "file",
        content: `#app { background: red; }`,
        language: "css",
    },
    {
        project: { id: 1},
        name: "index",
        extension: "js",
        type: "file",
        content: `document.getElementById('app').innerText = "Hello, JavaScript!";
        console.log("toto"); console.log({ a: 1, b: 2 }); console.log([1, 2, 3]);
        console.log("toto", [1, 2, 3]); console.log({ a: 1, b: 2 }, [1, 2, 3]);
        console.log("tototttttttt")
        console.log('arg1',[1,2,30], "arg2" ,{1:"toto",2:"ttt",3:"dddd"})`,
        language: "javascript",
    },
    {
        project: { id: 2},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 2},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 2},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
    {
        project: { id: 3},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 3},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 3},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
    {
        project: { id: 4},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 4},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 4},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
    {
        project: { id: 5},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 5},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 5},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
    {
        project: { id: 6},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 6},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 6},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
    {
        project: { id: 7},
        name: "index",
        extension: "html",
        type: "file",
        content: ``,
        language: "html",
    },
    {
        project: { id: 7},
        name: "style",
        extension: "css",
        type: "file",
        content: ``,
        language: "css",
    },
    {
        project: { id: 7},
        name: "index",
        extension: "js",
        type: "file",
        content: ``,
        language: "javascript",
    },
];

export default fakeFile;
