const fakeProjects = [
  {
    name: "The best Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The first Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The 3 Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The 4 Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The 8 Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The 5 Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },{
    name: "The 2 Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The 9 Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The tho Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The three Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The four Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The five Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The six Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

export default fakeProjects;
