const fakeProjects = [
  {
    name: "The best Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "1",
  },
  {
    name: "The first Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "2",
  },
  {
    name: "The tho Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "3",
  },
  {
    name: "The three Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "1",
  },
  {
    name: "The four Project",
    category: "JavaScript",
    private: true,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "2",
  },
  {
    name: "The five Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "1",
  },
  {
    name: "The six Project",
    category: "JavaScript",
    private: false,
    created_at: new Date(),
    updated_at: new Date(),
    // user_id: "4",
  },
];

export default fakeProjects;
