import { ROLE } from "../entities/user.entity";

const fakeUsers = [
  {
    lastname: "Renard",
    firstname: "Alexandre",
    pseudo: "Alexandre78R",
    email: "alexandre.renard98@gmail.com",
    password: "toto",
    role: "ADMIN"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "Millet",
    firstname: "Jean-Marc",
    pseudo: "JM",
    email: "jean-marc@example.com",
    password: "toto",
    role: "ADMIN"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "toto",
    firstname: "toto",
    pseudo: "toto",
    email: "toto@gmail.com",
    password: "toto",
    role: "ADMIN"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "tatz",
    firstname: "tatz",
    pseudo: "tatz",
    email: "tatz@gmail.com",
    password: "tatz",
    role: "USER"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "totz",
    firstname: "totz",
    pseudo: "totz",
    email: "totz@gmail.com",
    password: "totz",
    role: "USER"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "tutz",
    firstname: "tutz",
    pseudo: "tutz",
    email: "tutz@gmail.com",
    password: "tutz",
    role: "USER"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "Célia",
    firstname: "Brahmi",
    pseudo: "Célia",
    email: "Celia@gmail.com",
    password: "toto",
    role: "ADMIN"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "Doe",
    firstname: "John",
    pseudo: "johndoe",
    email: "john.doe@example.com",
    password: "password123",
    role: "USER"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    lastname: "d",
    firstname: "d",
    pseudo: "d",
    email: "john.dode@example.com",
    password: "password123",
    role: "USER"as ROLE,
    ban: false,
    run_counter: 0,
    last_login: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
  },
];

export default fakeUsers;